//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2Client) DeepCopyInto(out *OAuth2Client) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2Client.
func (in *OAuth2Client) DeepCopy() *OAuth2Client {
	if in == nil {
		return nil
	}
	out := new(OAuth2Client)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OAuth2Client) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2ClientList) DeepCopyInto(out *OAuth2ClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OAuth2Client, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2ClientList.
func (in *OAuth2ClientList) DeepCopy() *OAuth2ClientList {
	if in == nil {
		return nil
	}
	out := new(OAuth2ClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OAuth2ClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2ClientObservation) DeepCopyInto(out *OAuth2ClientObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2ClientObservation.
func (in *OAuth2ClientObservation) DeepCopy() *OAuth2ClientObservation {
	if in == nil {
		return nil
	}
	out := new(OAuth2ClientObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2ClientParameters) DeepCopyInto(out *OAuth2ClientParameters) {
	*out = *in
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.ClientName != nil {
		in, out := &in.ClientName, &out.ClientName
		*out = new(string)
		**out = **in
	}
	if in.ClientSecret != nil {
		in, out := &in.ClientSecret, &out.ClientSecret
		*out = new(string)
		**out = **in
	}
	if in.ClientURI != nil {
		in, out := &in.ClientURI, &out.ClientURI
		*out = new(string)
		**out = **in
	}
	if in.GrantTypes != nil {
		in, out := &in.GrantTypes, &out.GrantTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResponseTypes != nil {
		in, out := &in.ResponseTypes, &out.ResponseTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RedirectURIs != nil {
		in, out := &in.RedirectURIs, &out.RedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TokenEndpointAuthMethod != nil {
		in, out := &in.TokenEndpointAuthMethod, &out.TokenEndpointAuthMethod
		*out = new(string)
		**out = **in
	}
	if in.TokenEndpointAuthSigningAlg != nil {
		in, out := &in.TokenEndpointAuthSigningAlg, &out.TokenEndpointAuthSigningAlg
		*out = new(string)
		**out = **in
	}
	if in.Contacts != nil {
		in, out := &in.Contacts, &out.Contacts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LogoURI != nil {
		in, out := &in.LogoURI, &out.LogoURI
		*out = new(string)
		**out = **in
	}
	if in.PolicyURI != nil {
		in, out := &in.PolicyURI, &out.PolicyURI
		*out = new(string)
		**out = **in
	}
	if in.TosURI != nil {
		in, out := &in.TosURI, &out.TosURI
		*out = new(string)
		**out = **in
	}
	if in.AllowedCORSOrigins != nil {
		in, out := &in.AllowedCORSOrigins, &out.AllowedCORSOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Owner != nil {
		in, out := &in.Owner, &out.Owner
		*out = new(string)
		**out = **in
	}
	if in.SubjectType != nil {
		in, out := &in.SubjectType, &out.SubjectType
		*out = new(string)
		**out = **in
	}
	if in.SectorIdentifierURI != nil {
		in, out := &in.SectorIdentifierURI, &out.SectorIdentifierURI
		*out = new(string)
		**out = **in
	}
	if in.SkipConsent != nil {
		in, out := &in.SkipConsent, &out.SkipConsent
		*out = new(bool)
		**out = **in
	}
	if in.SkipLogoutConsent != nil {
		in, out := &in.SkipLogoutConsent, &out.SkipLogoutConsent
		*out = new(bool)
		**out = **in
	}
	if in.AccessTokenStrategy != nil {
		in, out := &in.AccessTokenStrategy, &out.AccessTokenStrategy
		*out = new(string)
		**out = **in
	}
	if in.BackchannelLogoutURI != nil {
		in, out := &in.BackchannelLogoutURI, &out.BackchannelLogoutURI
		*out = new(string)
		**out = **in
	}
	if in.BackchannelLogoutSessionRequired != nil {
		in, out := &in.BackchannelLogoutSessionRequired, &out.BackchannelLogoutSessionRequired
		*out = new(bool)
		**out = **in
	}
	if in.FrontchannelLogoutURI != nil {
		in, out := &in.FrontchannelLogoutURI, &out.FrontchannelLogoutURI
		*out = new(string)
		**out = **in
	}
	if in.FrontchannelLogoutSessionRequired != nil {
		in, out := &in.FrontchannelLogoutSessionRequired, &out.FrontchannelLogoutSessionRequired
		*out = new(bool)
		**out = **in
	}
	if in.PostLogoutRedirectURIs != nil {
		in, out := &in.PostLogoutRedirectURIs, &out.PostLogoutRedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequestObjectSigningAlg != nil {
		in, out := &in.RequestObjectSigningAlg, &out.RequestObjectSigningAlg
		*out = new(string)
		**out = **in
	}
	if in.RequestURIs != nil {
		in, out := &in.RequestURIs, &out.RequestURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UserinfoSignedResponseAlg != nil {
		in, out := &in.UserinfoSignedResponseAlg, &out.UserinfoSignedResponseAlg
		*out = new(string)
		**out = **in
	}
	if in.IDTokenSignedResponseAlg != nil {
		in, out := &in.IDTokenSignedResponseAlg, &out.IDTokenSignedResponseAlg
		*out = new(string)
		**out = **in
	}
	if in.JwksURI != nil {
		in, out := &in.JwksURI, &out.JwksURI
		*out = new(string)
		**out = **in
	}
	if in.Jwks != nil {
		in, out := &in.Jwks, &out.Jwks
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthorizationCodeGrantAccessTokenLifespan != nil {
		in, out := &in.AuthorizationCodeGrantAccessTokenLifespan, &out.AuthorizationCodeGrantAccessTokenLifespan
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationCodeGrantIDTokenLifespan != nil {
		in, out := &in.AuthorizationCodeGrantIDTokenLifespan, &out.AuthorizationCodeGrantIDTokenLifespan
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationCodeGrantRefreshTokenLifespan != nil {
		in, out := &in.AuthorizationCodeGrantRefreshTokenLifespan, &out.AuthorizationCodeGrantRefreshTokenLifespan
		*out = new(string)
		**out = **in
	}
	if in.ClientCredentialsGrantAccessTokenLifespan != nil {
		in, out := &in.ClientCredentialsGrantAccessTokenLifespan, &out.ClientCredentialsGrantAccessTokenLifespan
		*out = new(string)
		**out = **in
	}
	if in.ImplicitGrantAccessTokenLifespan != nil {
		in, out := &in.ImplicitGrantAccessTokenLifespan, &out.ImplicitGrantAccessTokenLifespan
		*out = new(string)
		**out = **in
	}
	if in.ImplicitGrantIDTokenLifespan != nil {
		in, out := &in.ImplicitGrantIDTokenLifespan, &out.ImplicitGrantIDTokenLifespan
		*out = new(string)
		**out = **in
	}
	if in.RefreshTokenGrantAccessTokenLifespan != nil {
		in, out := &in.RefreshTokenGrantAccessTokenLifespan, &out.RefreshTokenGrantAccessTokenLifespan
		*out = new(string)
		**out = **in
	}
	if in.RefreshTokenGrantIDTokenLifespan != nil {
		in, out := &in.RefreshTokenGrantIDTokenLifespan, &out.RefreshTokenGrantIDTokenLifespan
		*out = new(string)
		**out = **in
	}
	if in.RefreshTokenGrantRefreshTokenLifespan != nil {
		in, out := &in.RefreshTokenGrantRefreshTokenLifespan, &out.RefreshTokenGrantRefreshTokenLifespan
		*out = new(string)
		**out = **in
	}
	if in.JwtBearerGrantAccessTokenLifespan != nil {
		in, out := &in.JwtBearerGrantAccessTokenLifespan, &out.JwtBearerGrantAccessTokenLifespan
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2ClientParameters.
func (in *OAuth2ClientParameters) DeepCopy() *OAuth2ClientParameters {
	if in == nil {
		return nil
	}
	out := new(OAuth2ClientParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2ClientSpec) DeepCopyInto(out *OAuth2ClientSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2ClientSpec.
func (in *OAuth2ClientSpec) DeepCopy() *OAuth2ClientSpec {
	if in == nil {
		return nil
	}
	out := new(OAuth2ClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2ClientStatus) DeepCopyInto(out *OAuth2ClientStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2ClientStatus.
func (in *OAuth2ClientStatus) DeepCopy() *OAuth2ClientStatus {
	if in == nil {
		return nil
	}
	out := new(OAuth2ClientStatus)
	in.DeepCopyInto(out)
	return out
}
